bremersee:
  access:
    ip-addresses:
      - "127.0.0.1/32"
      - "::1"
  security:
    cors:
      allow-all: true
    oauth2:
      password-flow:
        client-id: omnia
        client-secret: changeit
        token-endpoint: https://openid.dev.bremersee.org/auth/realms/omnia/protocol/openid-connect/token
  exception-mapping:
    api-paths:
      - /api/**
  domain-controller:
    company-name: example.org
    company-url: http://example.org
    group-base-dn: ${LDAP_GROUP_DN:cn=Groups,dc=example,dc=org}
    user-base-dn: ${LDAP_USER_DN:cn=Users,dc=example,dc=org}
    name-server-host: ${NAME_SERVER_HOST:ns.example.org}
    dns-zone-base-dn: ${LDAP_ZONE_DN:CN=MicrosoftDNS,DC=DomainDnsZones,DC=example,DC=org}
    dns-node-base-dn: DC={zoneName},${bremersee.domain-controller.dns-zone-base-dn}
    mail-with-credentials:
      sender: ${spring.mail.username:no-reply@example.org}
      login-url: http://localhost:4200
  mail-template:
    resolvers:
      - prefix: "classpath:mail"
        resolvable-patterns:
          - "*"

eureka:
  client:
    enabled: ${EUREKA_CLIENT_ENABLED:false}
#    register-with-eureka: true
#    prefer-same-zone-eureka: true
#    service-url:
#      defaultZone: ${EUREKA_CLIENT_DEFAULT_ZONE:http://192.168.1.16:8761/eureka/}
#  instance:
#    health-check-url-path: /actuator/health
#    home-page-url-path: /actuator/info

logging:
  level:
    ROOT: info
    org.bremersee: debug
    org.springframework: info
#    org.springframework.security.oauth2: debug

management:
  endpoints:
    web:
      exposure:
        include: "*"
      cors:
        allowed-headers: "*"
        allowed-methods: "*"
        allowed-origins: "*"

server:
  port: ${SERVER_PORT:8090}

spring:
  jackson:
    date-format: com.fasterxml.jackson.databind.util.ISO8601DateFormat
    default-property-inclusion: non_null
    property-naming-strategy: LOWER_CAMEL_CASE
    locale: de_DE
    serialization:
      WRITE_DATES_AS_TIMESTAMPS: false
    time-zone: GMT
  sleuth:
    enabled: ${SLEUTH_ENABLED:false}
    sampler:
      probability: ${SLEUTH_PROBABILITY:1.0}
  zipkin:
    enabled: ${ZIPKIN_ENABLED:false}
    base-url: ${ZIPKIN_BASE_URL:http://localhost:9411/}
  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: https://keycloak.example.org/auth/realms/omnia/protocol/openid-connect/certs
  cache:
    jcache:
      config: classpath:ehcache.xml

---

spring:
  profiles: ldap

bremersee:
  ldaptive:
    ldap-url: ${LDAP_URL:ldaps://example.org:636}
    use-ssl: ${LDAP_SSL:true}
    use-start-tls: ${LDAP_START_TLS:false}
    bind-dn: ${LDAP_BIND_DN:areader@example.org}
    bind-credential: ${LDAP_BIND_PASSWORD:changeit}
    pooled: true
    min-pool-size: 3
    max-pool-size: 10
    validate-on-check-in: false
    validate-on-check-out: false
    validate-periodically: true
    validate-period: 300
    idle-time: 600
    block-wait-time: 10000
    search-validator:
      search-request:
        base-dn: ${LDAP_BASE_DN:dc=example,dc=org}
        search-filter:
          filter: ${LDAP_VALIDATION_FILTER:(cn=Administrator)}
        size-limit: 1
        search-scope: ONELEVEL
        return-attributes:
          - cn

---

spring:
  profiles: cli

---

spring:
  profiles: debian9

logging:
  path: /var/log/dc-con
  file:
    max-history: 25

server:
  tomcat:
    accesslog:
      enabled: true
      directory: /var/log/dc-con

---

spring:
  profiles: basic-auth

---

spring:
  profiles: test

bremersee:
  access:
    ip-addresses:
      - "8.8.8.0"
    basic-auth-users:
      - name: "admin"
        password: "admin"
        authorities:
          - "ROLE_LOCAL_USER"
          - "ROLE_ADMIN"
      - name: "actuator"
        password: "actuator"
        authorities:
          - "ROLE_ACTUATOR"
      - name: "user"
        password: "user"
        authorities:
          - "ROLE_LOCAL_USER"

---

spring:
  profiles: ide

bremersee:
  access:
    ip-addresses:
      - "8.8.8.0"

logging:
  level:
    ROOT: info
    org.bremersee: debug
    org.springframework: info
    org.springframework.security: debug
