bremersee:
  ldaptive:
    enabled: false
  security:
    cors:
      allow-all: true
    authentication:
      enable-jwt-support: ${JWT_SUPPORT:false}
      password-flow:
        client-id: ${OPENID_CLIENT_ID:omnia}
        client-secret: ${OPENID_CLIENT_SECRET:changeit}
        token-endpoint: ${OPENID_TOKEN_ENDPOINT:https://openid.dev.bremersee.org/auth/realms/omnia/protocol/openid-connect/token}
  exception-mapping:
    api-paths:
      - /api/**
    default-exception-mapping-config:
      include-stack-trace: true
      include-cause: true
      include-application-name: true
      include-exception-class-name: true
      include-handler: true
      include-path: true
  domain-controller:
    company-name: ${COMPANY_NAME:example.org}
    company-url: ${COMPANY_URL:http://example.org}
    group-base-dn: ${LDAP_GROUP_DN:cn=Groups,dc=example,dc=org}
    user-base-dn: ${LDAP_USER_DN:cn=Users,dc=example,dc=org}
    name-server-host: ${NAME_SERVER_HOST:ns.example.org}
    dns-zone-base-dn: ${LDAP_ZONE_DN:CN=MicrosoftDNS,DC=DomainDnsZones,DC=example,DC=org}
    dns-node-base-dn: DC={zoneName},${bremersee.domain-controller.dns-zone-base-dn}
    mail-with-credentials:
      sender: ${spring.mail.username:no-reply@example.org}
      login-url: http://localhost:4200/change-password
  thymeleaf:
    resolvers:
      - prefix: "classpath:mail/"
        suffix: ".html"
        resolvable-patterns:
          - "*"
        template-mode: HTML
  messages:
    default-locale: en
    fallback-to-system-locale: false

spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: https://keycloak.example.org/auth/realms/omnia/protocol/openid-connect/certs
  jackson:
    date-format: com.fasterxml.jackson.databind.util.ISO8601DateFormat
    default-property-inclusion: non_null
    property-naming-strategy: LOWER_CAMEL_CASE
    locale: de_DE
    serialization:
      WRITE_DATES_AS_TIMESTAMPS: false
    time-zone: GMT
  sleuth:
    enabled: ${SLEUTH_ENABLED:false}
    sampler:
      probability: ${SLEUTH_PROBABILITY:1.0}
  zipkin:
    enabled: ${ZIPKIN_ENABLED:false}
    base-url: ${ZIPKIN_BASE_URL:http://localhost:9411/}
  cache:
    jcache:
      config: classpath:ehcache.xml

management:
  endpoints:
    web:
      exposure:
        include: "*"
      cors:
        allowed-headers: "*"
        allowed-methods: "*"
        allowed-origins: "*"
  endpoint:
    health:
      show-details: always
  health:
    mail:
      enabled: false

server:
  forward-headers-strategy: native
  port: ${SERVER_PORT:8080}
  servlet:
    context-path: ${CONTEXT_PATH:/}
  tomcat:
    remote-ip-header: x-forwarded-for
    protocol-header: x-forwarded-proto
    port-header: x-forwarded-port
    accesslog:
      enabled: false

logging:
  level:
    ROOT: ${LOG_LEVEL_ROOT:INFO}
    org.springframework: ${LOG_LEVEL_SPRING:INFO}
    org.bremersee: ${LOG_LEVEL_BREMERSEE:DEBUG}

eureka:
  client:
    enabled: ${EUREKA_CLIENT_ENABLED:false}

---

spring:
  profiles: basic-auth

bremersee:
  security:
    authentication:
      enable-jwt-support: false
      basic-auth-users:
        - name: "admin"
          password: "admin"
          authorities:
            - "ROLE_LOCAL_USER"
            - "ROLE_ADMIN"
        - name: "actuator"
          password: "actuator"
          authorities:
            - "ROLE_ACTUATOR"
        - name: "user"
          password: "user"
          authorities:
            - "ROLE_LOCAL_USER"
      actuator:
        roles:
          - "ROLE_ACTUATOR"
          - "ROLE_ACTUATOR_ADMIN"
          - "ROLE_ADMIN"
        admin-roles:
          - "ROLE_ACTUATOR_ADMIN"
          - "ROLE_ADMIN"

---

spring:
  profiles: test

bremersee:
  security:
    authentication:
      actuator:
        ip-addresses:
          - "8.8.8.0"
      basic-auth-users:
        - name: "admin"
          password: "admin"
          authorities:
            - "ROLE_LOCAL_USER"
            - "ROLE_ADMIN"
        - name: "actuator"
          password: "actuator"
          authorities:
            - "ROLE_ACTUATOR"
        - name: "user"
          password: "user"
          authorities:
            - "ROLE_LOCAL_USER"

---

spring:
  profiles: ldap

bremersee:
  ldaptive:
    enabled: true
    ldap-url: ${LDAP_URL:ldaps://example.org:636}
    use-ssl: ${LDAP_SSL:true}
    use-start-tls: ${LDAP_START_TLS:false}
    bind-dn: ${LDAP_BIND_DN:areader@example.org}
    bind-credential: ${LDAP_BIND_PASSWORD:changeit}
    pooled: true
    min-pool-size: 3
    max-pool-size: 10
    validate-on-check-in: false
    validate-on-check-out: false
    validate-periodically: true
    validate-period: 300
    idle-time: 600
    block-wait-time: 10000
    search-validator:
      search-request:
        base-dn: ${LDAP_BASE_DN:dc=example,dc=org}
        search-filter:
          filter: ${LDAP_VALIDATION_FILTER:(cn=Administrator)}
        size-limit: 1
        search-scope: ONELEVEL
        return-attributes:
          - cn

---

spring:
  profiles: cli

---

spring:
  profiles: debian9

logging:
  file:
    name: /var/log/dc-con/dc-con.log
    max-history: 25

server:
  tomcat:
    accesslog:
      enabled: true
      directory: /var/log/dc-con
      prefix: access_log

